### ISSUE TITLE
1st May not clickable

### ISSUE THREAD

**Issue by ikeogu** [abhaywani114/osmanli_calender#1]
All 1st of other months are clickable except 1st May. please can be done to resolve this.
![image](https://user-images.githubusercontent.com/29304093/168764432-5dc52e66-37c5-4655-9f81-27d341068a20.png)

**Comment by abhaywani114** [comment]
can you share your code and console logs?

**Comment by ikeogu** [comment]
I managed to fix it

**Comment by abhaywani114** [comment]
Okay. Good luck buddy!
Give my greeting to Julian and Waisun ;-)
